CREATE TABLE `person` (
  `USER_ID` bigint(20) NOT NULL,
  `AADHAR_NO` varchar(100) NOT NULL,
  `NAME` varchar(50) NOT NULL,
  `LOCAL_NAME` varchar(100) DEFAULT NULL,
  `FATHER_NAME` varchar(50) DEFAULT NULL,
  `MOTHER_NAME` varchar(50) DEFAULT NULL,
  `GENDER` varchar(1) NOT NULL,
  `DOB` datetime NOT NULL,
  `DOB_TYPE` varchar(45) NOT NULL,
  `ADDRESS_ID` varchar(20) NOT NULL,
  `MOBILE` varchar(20) DEFAULT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`,`AADHAR_NO`),
  UNIQUE KEY `ADDRESS_ID_UNIQUE` (`ADDRESS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$