CREATE TABLE `address` (
  `ADDRESS_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CARE_OF` varchar(100) DEFAULT NULL,
  `LANDMARK` varchar(100) DEFAULT NULL,
  `LOCALITY` varchar(100) DEFAULT NULL,
  `VILLAGE_TOWN_CITY` varchar(100) DEFAULT NULL,
  `DISTRICT` varchar(100) DEFAULT NULL,
  `BUILDING` varchar(100) DEFAULT NULL,
  `STREET` varchar(100) DEFAULT NULL,
  `POST_OFFICE` varchar(100) DEFAULT NULL,
  `STATE` varchar(45) DEFAULT NULL,
  `PIN_CODE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ADDRESS_ID`),
  UNIQUE KEY `ADDRESS_ID_UNIQUE` (`ADDRESS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8$$