create table CHILD_PORTAL_USER(
	AADHAR_NO VARCHAR(100) NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	FATHER_NAME VARCHAR(50),
	MOTHER_NAME VARCHAR(50),
	GENDER VARCHAR(1) NOT NULL,
	DOB DATETIME NOT NULL,
	ADDRESS VARCHAR(100),
	DISTRICT VARCHAR(30),
	MOBILE VARCHAR(20),
	EMAIL VARCHAR(50)
)